- hosts: all
  become: yes
  tasks:
    
    - name: "Upload k8s-scripts-stage"
      copy:
        src: "k8s-scripts-stage"
        dest: "/root"

    - name: "Criando namespace"
      shell: kubectl apply -f ~/k8s-scripts-stage/namespace.yaml

    - name: "Aplicar configmap stage"
      shell: kubectl apply -f ~/k8s-scripts-stage/mysql-configmap.yaml

    - name: "Aplicar secret"
      shell: kubectl apply -f ~/k8s-scripts-stage/mysql-secret.yaml

    - name: "Aplicar deployment stage"
      shell: kubectl apply -f ~/k8s-scripts-stage/deployment.yaml

    - name: "Aplicar nodeport stage"
      shell: kubectl apply -f ~/k8s-scripts-stage/nodeport.yaml

    - shell: "kubectl get pods -n ns-java-stage | grep java-deployment-stage"
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "