- hosts: all
  become: yes
  tasks:
    
    - name: "Upload k8s-scripts"
      copy:
        src: "k8s-scripts"
        dest: "~/"

    - name: "Aplicar configmap dev"
      shell: kubectl apply -f ~/k8s-scripts/mysql-configmap-dev.yml

    - name: "Aplicar secret"
      shell: kubectl apply -f ~/k8s-scripts/mysql-secret.yml

    - name: "Aplicar deployment dev"
      shell: kubectl apply -f ~/k8s-scripts/deployment-dev.yml

    - name: "Aplicar nodeport dev"
      shell: kubectl apply -f ~/k8s-scripts/nodeport-javadb-dev.yml

    - shell: "kubectl get pods | grep java-deployment-dev"
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "