apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-javadb-prod
  namespace: ns-java-prod
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30200 # 30000 ~ 32767
  selector:
    app: pod-javadb-prod