apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment-stage
  namespace: ns-java-stage
spec:
  template:
    metadata:
      name: pod-javadb-stage
      labels:
        app: pod-javadb-stage
    spec:
      containers:
        - name: container-pod-javadb-stage
          image: manoel1845/projetofinal-spr-web
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-stage
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap-stage
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
  replicas: 1
  selector:
    matchLabels:
      app: pod-javadb-stage