apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-javadb-stage
  namespace: ns-java-stage
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30100 # 30000 ~ 32767
  selector:
    app: pod-javadb-stage